#!/usr/bin/env ksh
set -euo pipefail

PATH="/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
COLUMN=120

_header=$(mktemp /tmp/temail.XXXXXXX.zone)
_old_block=$(mktemp /tmp/temail.XXXXXXX.zone)
_block=$(mktemp /tmp/temail.XXXXXXX.zone)
typeset -i _serial_new=$(date +'%Y%m%d01')
typeset -i _serial_old=$(date +'%Y%m%d00')

_clean=$(cat <<-EOF
[ -f $_header ] && rm -f $_header;
[ -f $_block ] && rm -f $_block;
[ -f $_old_block ] && rm -f $_old_block;
EOF
)

_message () {
   typeset -u mtype # all value are converted to upper case
   local mpattern="%s: %s\n"
   local mtab=""
   mtype=${1:-"Error"}
   typeset -i numtab=${mtype%%[a-zA-Z]*}
   shift

   case $numtab in
       [1-9])
           for _ in $(seq -s" " ${numtab}); do
               mtab="\t$mtab"
           done
           ;;

   esac
   mpattern="$mtab$mpattern"
   mtype="${mtype#[0-9]}"

   if [[ ${mtype} == "ERROR"  ]]; then
      >&2 printf "$mpattern" $mtype "${@:-\"Something happends...\"}"
      exit 1
   else
       printf "$mpattern" $mtype "${@:-\"Something happends...\"}"
   fi
}

trap "$_clean" ERR EXIT

_out="/var/named/zones/adblock.zone"  # zone file

[ -f "$_out" ] || _message "Error" "Cannot alter file: $_out"

sed -e '1,/^;;--Domain/ !d' "$_out" > "$_header"
sed -e '1,/^;;--Domain/ d' "$_out" > "$_old_block"

# Check serial
_serial_old=$(sed -nE 's/^.[^0-9]+([[:digit:]]+).*;serial/\1/p' "$_header")

if [[ $_serial_new -le ${_serial_old:-0} ]] ; then
    _serial_new=$(($_serial_old + 1))
fi

# AdGuard Home
adguardhome() {
  # AdGuard DNS filter
  _src="https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
  ftp -MVo - "$_src" | \
  sed -nre 's/^\|\|([a-zA-Z0-9\_\-\.]+)\^.*$/\1@IN@CNAME@.@;NXDOMAIN policy/p'

  # AdGuard Français
  _src="https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/FrenchFilter/sections/adservers.txt"
  ftp -MVo - "$_src" | \
  sed -nre 's/^\|\|([a-zA-Z0-9\_\-\.]+)\^.*$/\1@IN@CNAME@.@;NXDOMAIN policy/p'

  # AdAway default blocklist
  _src="https://adaway.org/hosts.txt"
  ftp -MVo - "$_src" | \
  awk '/^127.0.0.1 / { print $2"@IN@CNAME@.@;NXDOMAIN policy" }' | \
  grep -v localhost
}

# From Pi-hole
stevenblack() {
  _src="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
  ftp -MVo - "$_src" | \
  awk '/^0.0.0.0 / {  print $2"@IN@CNAME@.@;NXDOMAIN policy"  }'
}


touch "$_out"
# Grab and format the data
adguardhome >> "$_block"
stevenblack >> "$_block"

# Clean entries and format entries
sed -r -e 's/\\//' \
       -e 's/\.\"/\"/' "$_block" |\
column -t -s '@' |\
sort -u -o "$_block"


# Take action is required
if $(diff -qb "$_old_block" "$_block" >/dev/null 2>&1 ); then
    _message 'Info' "Add block did not changed... skipping "
else
    # change serial
    sed -Ei "1,/;refresh/ s/(^[[:space:]]+)[0-9]+([[:space:]]+;serial.*$)/\1$_serial_new\2/" "$_header"
    cat $_header $_block > $_out
    chown _bind:_bind $_out
    named-checkzone adblock $_out
    if $(rndc -q status >/dev/null 2>&1); then
      rndc -q reload adblock >/dev/null 2>&1
    elif $(rcctl ls on | grep -qi isc_named); then
      rcctl restart isc_named
      sleep 5
      rndc -q reload >/dev/null 2>&1
    fi
fi
