#!/bin/ksh

daemon="/usr/local/bin/redis-sentinel"
daemon_flags="/var/redis/etc/sentinel.conf"
daemon_user="_redis"

. /etc/rc.d/rc.subr

pexp="redis-sentinel: ${daemon} .*"

rc_reload=NO

rc_pre() {
	/usr/bin/install -d -o _redis -g _redis -m 0750 /var/run/redis
}

rc_cmd $1
